spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthdb
    username: postgres
    password: shalani
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # auto-creates tables based on your @Entity classes
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
